- name: base
  label: 基本
  content:
    - name: enable_sw
      value: "0"
      label: 是否开启ServiceWorker
      desc:
      type: switch
    - name: cdn
      value:
      label: 静态资源CDN
      desc: 留空则不使用cdn
      type: text
    - name: footer
      value:
      label: 页脚html内容
      type: textarea
